# Generated by Django 6.1.1 on 2026-09-28 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Company Name')),
                ('job_role', models.CharField(max_length=200, verbose_name='Job Role')),
                ('package_lpa', models.DecimalField(decimal_places=2, help_text='Annual salary package in Lakhs Per Annum (e.g. 12.50)', max_digits=6, verbose_name='Package (LPA)')),
                ('min_cgpa', models.DecimalField(decimal_places=2, help_text='Minimum CGPA required to apply (e.g. 7.50)', max_digits=4, verbose_name='Minimum CGPA')),
                ('deadline', models.DateField(help_text='Last date to apply for this company', verbose_name='Application Deadline')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'ordering': ['deadline', 'name'],
            },
        ),
    ]
